[workspace]
authors = ["lnotspotl <lnotspotl@gmail.com>"]
channels = ["conda-forge"]
name = "tbai"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
gxx = "13.3.*"
fmt = "10.1.*"
spdlog = "1.12.0.*"
libtorch = { version = "==2.7.0", build = "*cpu_generic*" }
cpp-argparse = "*"
eigen="3.3.7.*"
gtest="*"
pybind11="2.13.6.*"
yaml-cpp="*"
pinocchio="3.7.*"
cmake="3.30.*"
just = ">=1.42.4,<2"
